/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  shopName: string;
  addressLine: string;
  city: string;
  phone: string;
  whatsapp: string;
  hoursOpen?: string;
  hoursClose?: string;
  openDays?: Array<string>;
  closedDay?: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
  deliveryNote?: string;
  mapLat?: number;
  mapLng?: number;
  mapEmbedUrl?: string;
  googleReviewUrl?: string;
  defaultSeo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  icon: "fitting" | "alignment" | "balancing";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  displayOrder?: number;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  brand: BrandReference;
  category: CategoryReference;
  width: number;
  profile: number;
  rim: number;
  sizeLabelOverride?: string;
  treadPattern?: string;
  loadIndex?: string;
  speedRating?: string;
  price: number;
  inStock?: boolean;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
    _key: string;
  }>;
  description?: string;
  featured?: boolean;
  seo?: Seo;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  icon: "car" | "suv" | "truck" | "forklift" | "offroad";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  displayOrder?: number;
  seo?: Seo;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  relationship: "importer" | "dealer" | "stocked";
  description?: string;
  displayOrder?: number;
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SiteSettings | Seo | SanityImageAssetReference | Service | SanityImageCrop | SanityImageHotspot | Slug | BrandReference | CategoryReference | Product | Category | Brand | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: HOMEPAGE_QUERY
// Query: {  "brands": *[_type == "brand"] | order(relationship asc, displayOrder asc) {    _id,    name,    "slug": slug.current,    relationship,    logo  },  "featuredProducts": *[_type == "product" && featured == true] | order(_createdAt desc) [0...8] {    _id,    name,    "slug": slug.current,    price,    inStock,    sizeLabelOverride,    treadPattern,    width,    profile,    rim,    images[]{ alt, asset },    brand->{ name, "slug": slug.current, relationship }  },  "categories": *[_type == "category"] | order(displayOrder asc) {    _id,    name,    "slug": slug.current,    icon  },  "services": *[_type == "service"] | order(displayOrder asc) [0...3] {    _id,    name,    "slug": slug.current,    icon  },  "settings": *[_type == "siteSettings"][0] {    shopName,    addressLine,    city,    phone,    whatsapp,    hoursOpen,    hoursClose,    openDays,    closedDay,    deliveryNote  }}
export type HOMEPAGE_QUERY_RESULT = {
  brands: Array<{
    _id: string;
    name: string;
    slug: string;
    relationship: "dealer" | "importer" | "stocked";
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
  featuredProducts: Array<{
    _id: string;
    name: string;
    slug: string;
    price: number;
    inStock: boolean | null;
    sizeLabelOverride: string | null;
    treadPattern: string | null;
    width: number;
    profile: number;
    rim: number;
    images: Array<{
      alt: string;
      asset: SanityImageAssetReference | null;
    }>;
    brand: {
      name: string;
      slug: string;
      relationship: "dealer" | "importer" | "stocked";
    };
  }>;
  categories: Array<{
    _id: string;
    name: string;
    slug: string;
    icon: "car" | "forklift" | "offroad" | "suv" | "truck";
  }>;
  services: Array<{
    _id: string;
    name: string;
    slug: string;
    icon: "alignment" | "balancing" | "fitting";
  }>;
  settings: {
    shopName: string;
    addressLine: string;
    city: string;
    phone: string;
    whatsapp: string;
    hoursOpen: string | null;
    hoursClose: string | null;
    openDays: Array<string> | null;
    closedDay: "Friday" | "Monday" | "Saturday" | "Sunday" | "Thursday" | "Tuesday" | "Wednesday" | null;
    deliveryNote: string | null;
  } | null;
};

// Source: src/lib/sanity/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[  _type == "product"  && (!defined($brandSlugs) || brand->slug.current in $brandSlugs)  && (!defined($categorySlug) || category->slug.current == $categorySlug)  && (!defined($width) || width == $width)  && (!defined($profile) || profile == $profile)  && (!defined($rim) || rim == $rim)  && (!defined($minPrice) || price >= $minPrice)  && (!defined($maxPrice) || price <= $maxPrice)  && (!defined($text) || [name, sizeLabelOverride, treadPattern, brand->name] match $text)] | order(featured desc, _createdAt desc) [$start...$end] {  _id,  name,  "slug": slug.current,  price,  inStock,  featured,  sizeLabelOverride,  treadPattern,  width,  profile,  rim,  images[]{ alt, asset },  brand->{ name, "slug": slug.current, relationship },  category->{ name, "slug": slug.current }}
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  inStock: boolean | null;
  featured: boolean | null;
  sizeLabelOverride: string | null;
  treadPattern: string | null;
  width: number;
  profile: number;
  rim: number;
  images: Array<{
    alt: string;
    asset: SanityImageAssetReference | null;
  }>;
  brand: {
    name: string;
    slug: string;
    relationship: "dealer" | "importer" | "stocked";
  };
  category: {
    name: string;
    slug: string;
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: PRODUCTS_COUNT_QUERY
// Query: count(*[  _type == "product"  && (!defined($brandSlugs) || brand->slug.current in $brandSlugs)  && (!defined($categorySlug) || category->slug.current == $categorySlug)  && (!defined($width) || width == $width)  && (!defined($profile) || profile == $profile)  && (!defined($rim) || rim == $rim)  && (!defined($minPrice) || price >= $minPrice)  && (!defined($maxPrice) || price <= $maxPrice)  && (!defined($text) || [name, sizeLabelOverride, treadPattern, brand->name] match $text)])
export type PRODUCTS_COUNT_QUERY_RESULT = number;

// Source: src/lib/sanity/queries.ts
// Variable: FILTER_OPTIONS_QUERY
// Query: {  "brands": *[_type == "brand"] | order(select(relationship == "importer" => 0, relationship == "dealer" => 1, 2) asc, displayOrder asc) {    name,    "slug": slug.current,    relationship  },  "categories": *[_type == "category"] | order(displayOrder asc) {    name,    "slug": slug.current  },  "widths": array::unique(*[_type == "product" && defined(width)].width),  "profiles": array::unique(*[_type == "product" && defined(profile)].profile),  "rims": array::unique(*[_type == "product" && defined(rim)].rim)}
export type FILTER_OPTIONS_QUERY_RESULT = {
  brands: Array<{
    name: string;
    slug: string;
    relationship: "dealer" | "importer" | "stocked";
  }>;
  categories: Array<{
    name: string;
    slug: string;
  }>;
  widths: Array<number>;
  profiles: Array<number>;
  rims: Array<number>;
};

// Source: src/lib/sanity/queries.ts
// Variable: PRODUCT_BY_SLUG
// Query: *[_type == "product" && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  price,  inStock,  featured,  sizeLabelOverride,  treadPattern,  width,  profile,  rim,  loadIndex,  speedRating,  description,  images[]{ alt, asset },  brand->{ _id, name, "slug": slug.current, relationship, logo },  category->{ _id, name, "slug": slug.current },  seo { title, description }}
export type PRODUCT_BY_SLUG_RESULT = {
  _id: string;
  name: string;
  slug: string;
  price: number;
  inStock: boolean | null;
  featured: boolean | null;
  sizeLabelOverride: string | null;
  treadPattern: string | null;
  width: number;
  profile: number;
  rim: number;
  loadIndex: string | null;
  speedRating: string | null;
  description: string | null;
  images: Array<{
    alt: string;
    asset: SanityImageAssetReference | null;
  }>;
  brand: {
    _id: string;
    name: string;
    slug: string;
    relationship: "dealer" | "importer" | "stocked";
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  };
  category: {
    _id: string;
    name: string;
    slug: string;
  };
  seo: {
    title: string | null;
    description: string | null;
  } | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: PRODUCT_SLUGS_QUERY
// Query: *[_type == "product"]{ "slug": slug.current }
export type PRODUCT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: RELATED_PRODUCTS_QUERY
// Query: *[  _type == "product"  && slug.current != $slug  && (brand._ref == $brandId || category._ref == $categoryId)] | order((brand._ref == $brandId) desc, _createdAt desc) [0...4] {  _id,  name,  "slug": slug.current,  price,  inStock,  sizeLabelOverride,  treadPattern,  width,  profile,  rim,  images[]{ alt, asset },  brand->{ name, "slug": slug.current, relationship }}
export type RELATED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  inStock: boolean | null;
  sizeLabelOverride: string | null;
  treadPattern: string | null;
  width: number;
  profile: number;
  rim: number;
  images: Array<{
    alt: string;
    asset: SanityImageAssetReference | null;
  }>;
  brand: {
    name: string;
    slug: string;
    relationship: "dealer" | "importer" | "stocked";
  };
}>;

// Source: src/lib/sanity/queries.ts
// Variable: BRANDS_QUERY
// Query: *[_type == "brand"] | order(select(relationship == "importer" => 0, relationship == "dealer" => 1, 2) asc, displayOrder asc) {  _id,  name,  "slug": slug.current,  relationship,  logo,  description}
export type BRANDS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  relationship: "dealer" | "importer" | "stocked";
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: BRAND_BY_SLUG
// Query: *[_type == "brand" && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  relationship,  logo,  description,  seo { title, description },  "products": *[_type == "product" && references(^._id)] | order(featured desc, _createdAt desc) {    _id,    name,    "slug": slug.current,    price,    inStock,    sizeLabelOverride,    treadPattern,    width,    profile,    rim,    images[]{ alt, asset },    brand->{ name, "slug": slug.current, relationship }  }}
export type BRAND_BY_SLUG_RESULT = {
  _id: string;
  name: string;
  slug: string;
  relationship: "dealer" | "importer" | "stocked";
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: string | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
  products: Array<{
    _id: string;
    name: string;
    slug: string;
    price: number;
    inStock: boolean | null;
    sizeLabelOverride: string | null;
    treadPattern: string | null;
    width: number;
    profile: number;
    rim: number;
    images: Array<{
      alt: string;
      asset: SanityImageAssetReference | null;
    }>;
    brand: {
      name: string;
      slug: string;
      relationship: "dealer" | "importer" | "stocked";
    };
  }>;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(displayOrder asc) {  _id,  name,  "slug": slug.current,  icon,  image{ alt, asset }}
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  icon: "car" | "forklift" | "offroad" | "suv" | "truck";
  image: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: CATEGORY_BY_SLUG
// Query: *[_type == "category" && slug.current == $slug][0]{  _id,  name,  "slug": slug.current,  description,  icon,  image{ alt, asset },  seo { title, description },  "products": *[_type == "product" && references(^._id)] | order(featured desc, _createdAt desc) {    _id,    name,    "slug": slug.current,    price,    inStock,    sizeLabelOverride,    treadPattern,    width,    profile,    rim,    images[]{ alt, asset },    brand->{ name, "slug": slug.current, relationship }  }}
export type CATEGORY_BY_SLUG_RESULT = {
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  icon: "car" | "forklift" | "offroad" | "suv" | "truck";
  image: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
  products: Array<{
    _id: string;
    name: string;
    slug: string;
    price: number;
    inStock: boolean | null;
    sizeLabelOverride: string | null;
    treadPattern: string | null;
    width: number;
    profile: number;
    rim: number;
    images: Array<{
      alt: string;
      asset: SanityImageAssetReference | null;
    }>;
    brand: {
      name: string;
      slug: string;
      relationship: "dealer" | "importer" | "stocked";
    };
  }>;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(displayOrder asc) {  _id,  name,  "slug": slug.current,  description,  icon,  image{ alt, asset },  seo { title, description }}
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
  icon: "alignment" | "balancing" | "fitting";
  image: {
    alt: string | null;
    asset: SanityImageAssetReference | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  shopName,  addressLine,  city,  phone,  whatsapp,  hoursOpen,  hoursClose,  openDays,  closedDay,  deliveryNote,  mapLat,  mapLng,  mapEmbedUrl,  googleReviewUrl,  defaultSeo { title, description }}
export type SETTINGS_QUERY_RESULT = {
  shopName: string;
  addressLine: string;
  city: string;
  phone: string;
  whatsapp: string;
  hoursOpen: string | null;
  hoursClose: string | null;
  openDays: Array<string> | null;
  closedDay: "Friday" | "Monday" | "Saturday" | "Sunday" | "Thursday" | "Tuesday" | "Wednesday" | null;
  deliveryNote: string | null;
  mapLat: number | null;
  mapLng: number | null;
  mapEmbedUrl: string | null;
  googleReviewUrl: string | null;
  defaultSeo: {
    title: string | null;
    description: string | null;
  } | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: SITEMAP_QUERY
// Query: {  "products": *[_type == "product"]{ "slug": slug.current, _updatedAt },  "brands": *[_type == "brand"]{ "slug": slug.current, _updatedAt },  "categories": *[_type == "category"]{ "slug": slug.current, _updatedAt },  "services": *[_type == "service"]{ "slug": slug.current, _updatedAt }}
export type SITEMAP_QUERY_RESULT = {
  products: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  brands: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  categories: Array<{
    slug: string;
    _updatedAt: string;
  }>;
  services: Array<{
    slug: string;
    _updatedAt: string;
  }>;
};

// Query TypeMap
declare global {
  interface SanityQueries {
    "{\n  \"brands\": *[_type == \"brand\"] | order(relationship asc, displayOrder asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    relationship,\n    logo\n  },\n  \"featuredProducts\": *[_type == \"product\" && featured == true] | order(_createdAt desc) [0...8] {\n    _id,\n    name,\n    \"slug\": slug.current,\n    price,\n    inStock,\n    sizeLabelOverride,\n    treadPattern,\n    width,\n    profile,\n    rim,\n    images[]{ alt, asset },\n    brand->{ name, \"slug\": slug.current, relationship }\n  },\n  \"categories\": *[_type == \"category\"] | order(displayOrder asc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    icon\n  },\n  \"services\": *[_type == \"service\"] | order(displayOrder asc) [0...3] {\n    _id,\n    name,\n    \"slug\": slug.current,\n    icon\n  },\n  \"settings\": *[_type == \"siteSettings\"][0] {\n    shopName,\n    addressLine,\n    city,\n    phone,\n    whatsapp,\n    hoursOpen,\n    hoursClose,\n    openDays,\n    closedDay,\n    deliveryNote\n  }\n}": HOMEPAGE_QUERY_RESULT;
    "*[\n  _type == \"product\"\n  && (!defined($brandSlugs) || brand->slug.current in $brandSlugs)\n  && (!defined($categorySlug) || category->slug.current == $categorySlug)\n  && (!defined($width) || width == $width)\n  && (!defined($profile) || profile == $profile)\n  && (!defined($rim) || rim == $rim)\n  && (!defined($minPrice) || price >= $minPrice)\n  && (!defined($maxPrice) || price <= $maxPrice)\n  && (!defined($text) || [name, sizeLabelOverride, treadPattern, brand->name] match $text)\n] | order(featured desc, _createdAt desc) [$start...$end] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  inStock,\n  featured,\n  sizeLabelOverride,\n  treadPattern,\n  width,\n  profile,\n  rim,\n  images[]{ alt, asset },\n  brand->{ name, \"slug\": slug.current, relationship },\n  category->{ name, \"slug\": slug.current }\n}": PRODUCTS_QUERY_RESULT;
    "count(*[\n  _type == \"product\"\n  && (!defined($brandSlugs) || brand->slug.current in $brandSlugs)\n  && (!defined($categorySlug) || category->slug.current == $categorySlug)\n  && (!defined($width) || width == $width)\n  && (!defined($profile) || profile == $profile)\n  && (!defined($rim) || rim == $rim)\n  && (!defined($minPrice) || price >= $minPrice)\n  && (!defined($maxPrice) || price <= $maxPrice)\n  && (!defined($text) || [name, sizeLabelOverride, treadPattern, brand->name] match $text)\n])": PRODUCTS_COUNT_QUERY_RESULT;
    "{\n  \"brands\": *[_type == \"brand\"] | order(select(relationship == \"importer\" => 0, relationship == \"dealer\" => 1, 2) asc, displayOrder asc) {\n    name,\n    \"slug\": slug.current,\n    relationship\n  },\n  \"categories\": *[_type == \"category\"] | order(displayOrder asc) {\n    name,\n    \"slug\": slug.current\n  },\n  \"widths\": array::unique(*[_type == \"product\" && defined(width)].width),\n  \"profiles\": array::unique(*[_type == \"product\" && defined(profile)].profile),\n  \"rims\": array::unique(*[_type == \"product\" && defined(rim)].rim)\n}": FILTER_OPTIONS_QUERY_RESULT;
    "*[_type == \"product\" && slug.current == $slug][0]{\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  inStock,\n  featured,\n  sizeLabelOverride,\n  treadPattern,\n  width,\n  profile,\n  rim,\n  loadIndex,\n  speedRating,\n  description,\n  images[]{ alt, asset },\n  brand->{ _id, name, \"slug\": slug.current, relationship, logo },\n  category->{ _id, name, \"slug\": slug.current },\n  seo { title, description }\n}": PRODUCT_BY_SLUG_RESULT;
    "*[_type == \"product\"]{ \"slug\": slug.current }": PRODUCT_SLUGS_QUERY_RESULT;
    "*[\n  _type == \"product\"\n  && slug.current != $slug\n  && (brand._ref == $brandId || category._ref == $categoryId)\n] | order((brand._ref == $brandId) desc, _createdAt desc) [0...4] {\n  _id,\n  name,\n  \"slug\": slug.current,\n  price,\n  inStock,\n  sizeLabelOverride,\n  treadPattern,\n  width,\n  profile,\n  rim,\n  images[]{ alt, asset },\n  brand->{ name, \"slug\": slug.current, relationship }\n}": RELATED_PRODUCTS_QUERY_RESULT;
    "*[_type == \"brand\"] | order(select(relationship == \"importer\" => 0, relationship == \"dealer\" => 1, 2) asc, displayOrder asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  relationship,\n  logo,\n  description\n}": BRANDS_QUERY_RESULT;
    "*[_type == \"brand\" && slug.current == $slug][0]{\n  _id,\n  name,\n  \"slug\": slug.current,\n  relationship,\n  logo,\n  description,\n  seo { title, description },\n  \"products\": *[_type == \"product\" && references(^._id)] | order(featured desc, _createdAt desc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    price,\n    inStock,\n    sizeLabelOverride,\n    treadPattern,\n    width,\n    profile,\n    rim,\n    images[]{ alt, asset },\n    brand->{ name, \"slug\": slug.current, relationship }\n  }\n}": BRAND_BY_SLUG_RESULT;
    "*[_type == \"category\"] | order(displayOrder asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  icon,\n  image{ alt, asset }\n}": CATEGORIES_QUERY_RESULT;
    "*[_type == \"category\" && slug.current == $slug][0]{\n  _id,\n  name,\n  \"slug\": slug.current,\n  description,\n  icon,\n  image{ alt, asset },\n  seo { title, description },\n  \"products\": *[_type == \"product\" && references(^._id)] | order(featured desc, _createdAt desc) {\n    _id,\n    name,\n    \"slug\": slug.current,\n    price,\n    inStock,\n    sizeLabelOverride,\n    treadPattern,\n    width,\n    profile,\n    rim,\n    images[]{ alt, asset },\n    brand->{ name, \"slug\": slug.current, relationship }\n  }\n}": CATEGORY_BY_SLUG_RESULT;
    "*[_type == \"service\"] | order(displayOrder asc) {\n  _id,\n  name,\n  \"slug\": slug.current,\n  description,\n  icon,\n  image{ alt, asset },\n  seo { title, description }\n}": SERVICES_QUERY_RESULT;
    "*[_type == \"siteSettings\"][0]{\n  shopName,\n  addressLine,\n  city,\n  phone,\n  whatsapp,\n  hoursOpen,\n  hoursClose,\n  openDays,\n  closedDay,\n  deliveryNote,\n  mapLat,\n  mapLng,\n  mapEmbedUrl,\n  googleReviewUrl,\n  defaultSeo { title, description }\n}": SETTINGS_QUERY_RESULT;
    "{\n  \"products\": *[_type == \"product\"]{ \"slug\": slug.current, _updatedAt },\n  \"brands\": *[_type == \"brand\"]{ \"slug\": slug.current, _updatedAt },\n  \"categories\": *[_type == \"category\"]{ \"slug\": slug.current, _updatedAt },\n  \"services\": *[_type == \"service\"]{ \"slug\": slug.current, _updatedAt }\n}": SITEMAP_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}

